<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="kevins-iMac.local" name="Test" tests="14" failures="8" timestamp="26 Dec 2013 09:22:56 GMT" time="4.054" errors="0">
  <testcase name="@BeforeMethod setUp" time="0.0" classname="com.netease.qa.testng.demo.Fail1SkipTest">
    <failure type="java.lang.AssertionError" message="skip">
      <![CDATA[java.lang.AssertionError: skip
	at com.netease.qa.testng.demo.Fail1SkipTest.setUp(Fail1SkipTest.java:27)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@BeforeMethod setUp" time="0.0" classname="com.netease.qa.testng.demo.SkipTest">
    <failure type="java.lang.AssertionError" message="skip">
      <![CDATA[java.lang.AssertionError: skip
	at com.netease.qa.testng.demo.SkipTest.setUp(SkipTest.java:21)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="com.netease.qa.testng.demo.Fail3Test">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.netease.qa.testng.demo.Fail3Test.tearDown(Fail3Test.java:46)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setUp" time="0.0" classname="com.netease.qa.testng.demo.Fail3Test">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="com.netease.qa.testng.demo.Fail3Test">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="testFail1Skip" time="0.0020" classname="com.netease.qa.testng.demo.Fail1SkipTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.netease.qa.testng.demo.Fail1SkipTest.testFail1Skip(Fail1SkipTest.java:34)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testFail1Skip -->
  <testcase name="testFail1Skip" time="0.0" classname="com.netease.qa.testng.demo.Fail1SkipTest">
    <skipped/>
  </testcase> <!-- testFail1Skip -->
  <testcase name="testFail1Sussces" time="0.0" classname="com.netease.qa.testng.demo.Fail1SuccessTest">
    <failure type="java.lang.AssertionError" message="FailSussces2">
      <![CDATA[java.lang.AssertionError: FailSussces2
	at com.netease.qa.testng.demo.Fail1SuccessTest.testFail1Sussces(Fail1SuccessTest.java:29)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testFail1Sussces -->
  <testcase name="testFail1Sussces" time="0.0" classname="com.netease.qa.testng.demo.Fail1SuccessTest"/>
  <testcase name="testFail2Sussces" time="0.0" classname="com.netease.qa.testng.demo.Fail2SuccessTest">
    <failure type="java.lang.AssertionError" message="testFail2Sussces">
      <![CDATA[java.lang.AssertionError: testFail2Sussces
	at com.netease.qa.testng.demo.Fail2SuccessTest.testFail2Sussces(Fail2SuccessTest.java:28)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testFail2Sussces -->
  <testcase name="testFail2Sussces" time="0.0010" classname="com.netease.qa.testng.demo.Fail2SuccessTest">
    <failure type="java.lang.AssertionError" message="testFail2Sussces">
      <![CDATA[java.lang.AssertionError: testFail2Sussces
	at com.netease.qa.testng.demo.Fail2SuccessTest.testFail2Sussces(Fail2SuccessTest.java:28)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testFail2Sussces -->
  <testcase name="testFail2Sussces" time="0.0" classname="com.netease.qa.testng.demo.Fail2SuccessTest"/>
  <testcase name="testSkip" time="0.0" classname="com.netease.qa.testng.demo.SkipTest">
    <skipped/>
  </testcase> <!-- testSkip -->
  <testcase name="testFail3" time="1.002" classname="com.netease.qa.testng.demo.Fail3Test">
    <failure type="java.lang.AssertionError" message="testFail3">
      <![CDATA[java.lang.AssertionError: testFail3
	at com.netease.qa.testng.demo.Fail3Test.testFail3(Fail3Test.java:38)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testFail3 -->
  <testcase name="testFail3" time="1.002" classname="com.netease.qa.testng.demo.Fail3Test">
    <failure type="java.lang.AssertionError" message="testFail3">
      <![CDATA[java.lang.AssertionError: testFail3
	at com.netease.qa.testng.demo.Fail3Test.testFail3(Fail3Test.java:38)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testFail3 -->
  <testcase name="testFail3" time="1.002" classname="com.netease.qa.testng.demo.Fail3Test">
    <failure type="java.lang.AssertionError" message="testFail3">
      <![CDATA[java.lang.AssertionError: testFail3
	at com.netease.qa.testng.demo.Fail3Test.testFail3(Fail3Test.java:38)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testFail3 -->
  <testcase name="testFail3" time="1.002" classname="com.netease.qa.testng.demo.Fail3Test">
    <failure type="java.lang.AssertionError" message="testFail3">
      <![CDATA[java.lang.AssertionError: testFail3
	at com.netease.qa.testng.demo.Fail3Test.testFail3(Fail3Test.java:38)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testFail3 -->
  <testcase name="testFail3" time="0.0" classname="com.netease.qa.testng.demo.Fail3Test">
    <skipped/>
  </testcase> <!-- testFail3 -->
  <testcase name="testSuccess" time="0.0" classname="com.netease.qa.testng.demo.SuccessTest"/>
</testsuite> <!-- Test -->
