<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" total="6" passed="3">
  <reporter-output>
    <line>
      <![CDATA[RunCount=2]]>
    </line>
    <line>
      <![CDATA[RunCount=2]]>
    </line>
    <line>
      <![CDATA[RunCount=2]]>
    </line>
    <line>
      <![CDATA[RunCount=3]]>
    </line>
    <line>
      <![CDATA[RunCount=2]]>
    </line>
    <line>
      <![CDATA[RunCount=3]]>
    </line>
    <line>
      <![CDATA[RunCount=4]]>
    </line>
    <line>
      <![CDATA[RunCount=5]]>
    </line>
  </reporter-output>
  <suite name="Pris_iOS_UI_AutoTest" duration-ms="4054" started-at="2013-12-26T09:22:52Z" finished-at="2013-12-26T09:22:56Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="4054" started-at="2013-12-26T09:22:52Z" finished-at="2013-12-26T09:22:56Z">
      <class name="com.netease.qa.testng.demo.Fail1SuccessTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail1SuccessTest@15e232b5]" name="setUp" is-config="true" duration-ms="1" started-at="2013-12-26T17:22:52Z" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testFail1Sussces()[pri:0, instance:com.netease.qa.testng.demo.Fail1SuccessTest@15e232b5]" name="testFail1Sussces" duration-ms="0" started-at="2013-12-26T17:22:52Z" description="testFail1Sussces" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFail1Sussces -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail1SuccessTest@15e232b5]" name="setUp" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:52Z" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- com.netease.qa.testng.demo.Fail1SuccessTest -->
      <class name="com.netease.qa.testng.demo.Fail3Test">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="setUp" is-config="true" duration-ms="1" started-at="2013-12-26T17:22:52Z" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="tearDown" is-config="true" duration-ms="1" started-at="2013-12-26T17:22:53Z" finished-at="2013-12-26T17:22:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="setUp" is-config="true" duration-ms="1" started-at="2013-12-26T17:22:53Z" finished-at="2013-12-26T17:22:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="tearDown" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:54Z" finished-at="2013-12-26T17:22:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="setUp" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:54Z" finished-at="2013-12-26T17:22:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="tearDown" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:55Z" finished-at="2013-12-26T17:22:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="setUp" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:55Z" finished-at="2013-12-26T17:22:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="tearDown" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:56Z" finished-at="2013-12-26T17:22:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.netease.qa.testng.demo.Fail3Test.tearDown(Fail3Test.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.TestNG.privateMain(TestNG.java:1338)
	at org.testng.TestNG.main(TestNG.java:1307)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="testFail3()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="testFail3" duration-ms="0" started-at="2013-12-26T17:22:56Z" description="testFail3" finished-at="2013-12-26T17:22:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFail3 -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="tearDown" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:56Z" finished-at="2013-12-26T17:22:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail3Test@236acdd1]" name="setUp" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:56Z" finished-at="2013-12-26T17:22:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- com.netease.qa.testng.demo.Fail3Test -->
      <class name="com.netease.qa.testng.demo.Fail1SkipTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail1SkipTest@15f48262]" name="setUp" is-config="true" duration-ms="7" started-at="2013-12-26T17:22:52Z" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail1SkipTest@15f48262]" name="setUp" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:52Z" finished-at="2013-12-26T17:22:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[skip]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: skip
	at org.testng.Assert.fail(Assert.java:94)
	at com.netease.qa.testng.demo.Fail1SkipTest.setUp(Fail1SkipTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.TestNG.privateMain(TestNG.java:1338)
	at org.testng.TestNG.main(TestNG.java:1307)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="testFail1Skip()[pri:0, instance:com.netease.qa.testng.demo.Fail1SkipTest@15f48262]" name="testFail1Skip" duration-ms="0" started-at="2013-12-26T17:22:52Z" description="testFail1Skip" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFail1Skip -->
      </class> <!-- com.netease.qa.testng.demo.Fail1SkipTest -->
      <class name="com.netease.qa.testng.demo.Fail2SuccessTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail2SuccessTest@60de1b8a]" name="setUp" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:52Z" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail2SuccessTest@60de1b8a]" name="setUp" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:52Z" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.Fail2SuccessTest@60de1b8a]" name="setUp" is-config="true" duration-ms="1" started-at="2013-12-26T17:22:52Z" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testFail2Sussces()[pri:0, instance:com.netease.qa.testng.demo.Fail2SuccessTest@60de1b8a]" name="testFail2Sussces" duration-ms="0" started-at="2013-12-26T17:22:52Z" description="testFail2Sussces" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFail2Sussces -->
      </class> <!-- com.netease.qa.testng.demo.Fail2SuccessTest -->
      <class name="com.netease.qa.testng.demo.SuccessTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.SuccessTest@402f0df1]" name="setUp" is-config="true" duration-ms="1" started-at="2013-12-26T17:22:56Z" finished-at="2013-12-26T17:22:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testSuccess()[pri:0, instance:com.netease.qa.testng.demo.SuccessTest@402f0df1]" name="testSuccess" duration-ms="0" started-at="2013-12-26T17:22:56Z" description="testSuccess" finished-at="2013-12-26T17:22:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccess -->
      </class> <!-- com.netease.qa.testng.demo.SuccessTest -->
      <class name="com.netease.qa.testng.demo.SkipTest">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:com.netease.qa.testng.demo.SkipTest@356f144c]" name="setUp" is-config="true" duration-ms="0" started-at="2013-12-26T17:22:52Z" finished-at="2013-12-26T17:22:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[skip]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: skip
	at org.testng.Assert.fail(Assert.java:94)
	at com.netease.qa.testng.demo.SkipTest.setUp(SkipTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.TestNG.privateMain(TestNG.java:1338)
	at org.testng.TestNG.main(TestNG.java:1307)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="testSkip()[pri:0, instance:com.netease.qa.testng.demo.SkipTest@356f144c]" name="testSkip" duration-ms="0" started-at="2013-12-26T17:22:52Z" description="TestSkip" finished-at="2013-12-26T17:22:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkip -->
      </class> <!-- com.netease.qa.testng.demo.SkipTest -->
    </test> <!-- Test -->
  </suite> <!-- Pris_iOS_UI_AutoTest -->
</testng-results>
